[libraries]
th2-bom = { group = "com.exactpro.th2", name = "bom", version = "4.14.2" }
kotlin-logging = { group = "io.github.oshai", name = "kotlin-logging", version = "5.1.4" }

javapoet = { group = "com.squareup", name = "javapoet", version = "1.13.0" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version = "6.0.1" }

[plugins]
th2-publish = { id = "com.exactpro.th2.gradle.publish", version = "0.3.10" }
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "1.8.22" }